<?php
/**
 * Created by PhpStorm.
 * User: xudonghai
 * Date: 2017/3/13 9:27
 * 继承重写urlmanage类，使其支持多域名，注意：CUrlManage中的键，必须跟模块下配置文件main中的id一致，否则在默认不传标识的情况下，找不到rules规则
 * 例如生成图片模块车系首页
 * 基本用法：Yii::$app->CUrlManage->createHostUrl(['控制器/方法','参数名'=>参数值],'CUrlManage中配置的键值名，例如photos')
 * 精简用法：$this->createHostUrl(['控制器/方法','参数名'=>参数值],'CUrlManage中配置的键值名，例如photos')
 * demo: 生成图片模块车系首页 => $this->createHostUrl(['site/index','id'=>123]， HOST_WWW) = photo.carnew.com/123
 */
namespace common\components;

use yii;
use yii\web\UrlManager;
use yii\base\InvalidConfigException;

class CUrlManager extends UrlManager
{
    public function init()
    {
        $this->cacheKey .=$_SERVER['HTTP_HOST'];
        return parent::init(); // TODO: Change the autogenerated stub
    }
}