<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/31
 * Time: 17:29
 */
namespace http\controllers;
use Yii;
use yii\web\Controller;

class BaseController extends Controller{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub


    }

}